blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [   
    # 카테고리 관리
    path('category/', views.category_list, name='category_list'), # 카테고리 나열 - DB에서 카테고리 리스트를 조회 -> template
    path('category/add/', views.category_add, name='category_add'), # 카테고리 추가
    path('category/<int:category_id>', views.category_post_list, name='category_post_list' ), # 특정 카테고리에 속한 post 보여주기

    # # 게시글 관련 URL
    path("", views.index, name='index'), # 전체 포스트의 나열, 리스트 표시, 카테고리에 상관없이 시간순 내림차순 -> 카테고리로 나열화면으로 가는 링크 추가
    path('post/<int:post_id>', views.post_detail, name='post_detail'), # 한 포스트에 대한 세부내용(블로그 내용 표시)
    path('post/write/<int:category_id>/', views.post_write, name='post_write'), # 포스트 생성
    path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'), # 포스트 편집(update)
    path('post/<int:post_id>/delete', views.post_delete, name='post_delete'), # 포스트 삭제
    # Search
    path('search/', views.search, name='search'),
]

# 10:50까지 개선사항이나 버그에 대한 아이디어를 피들렛에 댓글로 남겨주세요!

cafe/urls.py
from django.urls import path
from . import views
app_name="cafe"
urlpatterns = [    
    path('', views.index_view, name='cafe_home'),
    path('menu_list_url/', views.menu_list, name="menu_list_page"),
    path('menu_add_url/',views.menu_add, name="menu_add_page"), # 메뉴 추가 페이지
    path('add_menu_data/', views.add_menu_data, name='add_menu_data'),
    # 메뉴 디테일 페이지 추가
    path('detail/<int:menu_id>/', views.menu_detail, name="menu_detail"),
    path('add_option/<int:menu_id>/', views.add_option, name='add_option'),
    path('add_option_data/', views.add_option_data, name='add_option_data'),
    path('create/', views.create, name="menu_create"),
    path('<int:pk>/update/', views.update, name="menu_update"),
    path('<int:pk>/delete/', views.delete, name="menu_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', views.UserCreateDoneTV.as_view(), name='register_done'),
    path("",views.HomeView.as_view(), name='index') ,
    path("cafe/", include("cafe.urls")),
    path("blog/", include("blog.urls")),
    path("imageapp/", include("imageapp.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),        
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imageapp/urls.py
from django.urls import path
from . import views

app_name='imageapp'

urlpatterns = [   
    # 카테고리 관리
    path('', views.index, name='index'), 
    path('image/write/', views.image_write, name="image_write"),
    path('image/<int:image_id>', views.image_detail, name='image_detail'),
    path('image/<int:image_id>/edit/', views.image_edit, name='image_edit'), # 이미지 편집(update)
    path('image/<int:image_id>/delete/', views.image_delete, name='image_delete'),
    # 구독
    # path('image/<int:image_id>/toggle_subscribe', views.toggle_subscribe, name='toggle_subscribe')
    # 구독 json return
    path('image/<int:image_id>/subscribe/', views.toggle_subscription, name='toggle_subscription')
]

config/views.py
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
class HomeView(generic.TemplateView):
    template_name='home.html'

class UserCreateView(generic.CreateView):
    template_name='registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(generic.TemplateView):
    template_name='registration/register_done.html'

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}base.html{% endblock %}</title>

    <script src="https://cdn.jsdelivr.net/npm/axios@1.6.2/dist/axios.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% block extra-style %}{% endblock %}
</head>
<body class="container">
    <nav class="navbar bg-primary navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">LiONsnow</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <form class="d-flex" role="search" action="{% url 'blog:search' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" style="width: 50px; height: 40px; padding: 5px;">
                <button class="btn btn-outline-success" type="submit" style="height: 40px; padding: 0 10px; font-size: 12px;">Search</button>
              </form>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">.</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'cafe:cafe_home' %}"> 카페사나리아 </a>
              </li>              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'imageapp:index' %}"> ImageApp </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:index' %}"> Blog </a>
              </li>
              <li class="nav-item d-flex align-items-center">
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-danger me-2" type="submit" style="height: 40px; padding: 0 10px; font-size: 12px;">Logout</button>
                    </form>
                    <a class="btn btn-outline-secondary" href="{% url 'password_change'%}" style="height: 40px; padding: 1 0px; font-size: 12px;">{{ user.username }} pwdchg</a>
                {% else %}
                    <a class="btn btn-primary text-white me-2" href="{% url 'login' %}" style="height: 40px; padding: 0 10px; font-size: 12px;">Login</a>
                    <a class="btn btn-outline-primary" href="{% url 'register' %}" style="height: 40px; padding: 0 10px; font-size: 12px;">Regi</a>
                {% endif %}
            </li>         
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                추가
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/admin/">Admin</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
              </li>
              <!-- <li>
                {% if user.is_authenticated %}
                <span class="btn btn-primary btn-sm text-white me-2 py-2" aria-current="page">
                  Login : {{ user.username }}
                </span>
              {% endif %}  
              </li> -->
            </ul>
          </div>
        </div>
      </nav>

      {% block content %}
    <h1>나는 멋쟁이 백엔드 개발자!!!</h1>
    {% endblock %}
    {% block footer %}
    <footer class="bg-dark text-white py-4 fixed-bottom container">
      <div class="container">

        <h4>Like Lion Backend Django </h4>
        <p>Copyright by Lion 2024</p>
      </div>
    </footer> 
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

config/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
    .home-image {
        background-image: url("{% static 'images/lion1.jpg' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    }
    .title {
        color: rgb(204, 36, 50);
        font-weight: bold;
        text-align: right;
    }
    .powered {
        position: relative;
        top: 77%;
        color: rgb(255, 7, 255);
        font-style: italic;
    }
    </style>
{% endblock %}

{% block content %}
<div class="home-image">
    <h2 class="title">Django - Lion Web Programming</h4>
    <h4 class="powered">python + django + cloud + cicd....</h4>
</div>

<h1>우리는 장고 개발자입니다!!!</h1>

{% endblock %}